#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="${0:A:h}"
REPOSITORY_ROOT="${SCRIPT_DIR:h}"
PROJECT_FILE="${PROJECT_FILE:-$REPOSITORY_ROOT/MarkLens.xcodeproj/project.pbxproj}"
BUILD_INFO_FILE="${BUILD_INFO_FILE:-$REPOSITORY_ROOT/MarkLens/BuildInfo.swift}"

if [[ -z "${CI_TAG:-}" ]]; then
    echo "No CI_TAG set; leaving MARKETING_VERSION and CURRENT_PROJECT_VERSION unchanged."
    exit 0
fi

if [[ ! -f "$PROJECT_FILE" ]]; then
    echo "error: Expected project file at $PROJECT_FILE"
    exit 1
fi

TAG_VERSION="${CI_TAG#refs/tags/}"
TAG_VERSION="${TAG_VERSION#v}"

if [[ ! "$TAG_VERSION" =~ '^[0-9]+(\.[0-9]+){1,2}(-[A-Za-z][A-Za-z0-9]*(\.[A-Za-z0-9]+)*)?$' ]]; then
    echo "error: CI_TAG '$CI_TAG' does not look like a release tag such as v1.0.0, v1.0.1-test, or v1.0.1-rc1"
    exit 1
fi

VERSION="${TAG_VERSION%%-*}"

BUILD_NUMBER="${CI_BUILD_NUMBER:-}"
if [[ -z "$BUILD_NUMBER" ]]; then
    BUILD_NUMBER="$(git rev-list --count HEAD)"
fi
SHORT_COMMIT="$(git rev-parse --short=12 HEAD)"

if [[ ! "$BUILD_NUMBER" =~ '^[0-9]+$' ]]; then
    echo "error: Build number '$BUILD_NUMBER' is not numeric"
    exit 1
fi

echo "Setting MARKETING_VERSION to $VERSION from CI_TAG=$CI_TAG"
if [[ "$TAG_VERSION" == *-* ]]; then
    echo "Ignoring prerelease suffix for Apple's numeric MARKETING_VERSION."
fi
echo "Setting CURRENT_PROJECT_VERSION to $BUILD_NUMBER"
echo "Writing build metadata with release tag $CI_TAG and commit $SHORT_COMMIT"

perl -0pi -e "s/MARKETING_VERSION = [^;]+;/MARKETING_VERSION = $VERSION;/g" "$PROJECT_FILE"
perl -0pi -e "s/CURRENT_PROJECT_VERSION = [^;]+;/CURRENT_PROJECT_VERSION = $BUILD_NUMBER;/g" "$PROJECT_FILE"

cat > "$BUILD_INFO_FILE" <<EOF
//
//  BuildInfo.swift
//  MarkLens
//
//  Generated by ci_scripts/ci_pre_xcodebuild.sh.
//

import Foundation

enum BuildInfo {
    nonisolated static let releaseTag = "$CI_TAG"
    nonisolated static let tagVersion = "$TAG_VERSION"
    nonisolated static let shortCommit = "$SHORT_COMMIT"

    static var marketingVersion: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "0"
    }

    static var buildNumber: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "0"
    }

    static var displayVersion: String {
        marketingVersion
    }

    static var releaseDescription: String {
        "Release: \\(releaseTag)\\nCommit: \\(shortCommit)"
    }
}
EOF

echo "Version settings updated for Xcode Cloud build."
